Lecture8/hw
alice-rami/react-course-2023-11 pull request #8
Opened 2023-12-10 18:55 UTC by alice-rami

2023-12-11 15:12 UTC, SArchieEdu requested changes

2023-12-11 15:12 UTC, SArchieEdu commented on src/redux/entities/dish/get-dishes/get-dishes.ts
> +      const { dishes } = getState() as RootState;
лучше селекторами

2023-12-11 15:12 UTC, SArchieEdu commented on src/redux/entities/dish/index.ts
> +  restaurantIds: [],
покажу на лекции как проще сделать, без добавления нового поля

2023-12-12 20:02 UTC, alice-rami commented on src/redux/entities/dish/index.ts
> +  restaurantIds: [],
Спасибо!

2023-12-14 13:20 UTC, SArchieEdu approved these changes

2023-12-15 14:47 UTC, merged